# Generated by Django 6.0 on 2026-01-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Smart Watch', 'Smart Watch'), ('Tablet', 'Tablet')], max_length=20, null=True),
        ),
    ]
