# Generated by Django 6.0 on 2026-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_company_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Urea', 'Urea'), ('DAP', 'DAP'), ('NPK', 'NPK'), ('MOP', 'MOP'), ('Organic', 'Organic'), ('Bio-Fertilizer', 'Bio-Fertilizer'), ('Pesticide', 'Pesticide'), ('Seeds', 'Seeds')], max_length=20, null=True),
        ),
    ]
